FROM php:8.2-apache

# Estensioni utili
RUN docker-php-ext-install pdo pdo_mysql

# Abilita mod_rewrite (routing)
RUN a2enmod rewrite

RUN printf '<Directory /var/www/html>\n\
    AllowOverride All\n\
    Require all granted\n\
</Directory>\n' > /etc/apache2/conf-available/allowoverride.conf \
 && a2enconf allowoverride

WORKDIR /var/www/html

EXPOSE 80
