---
config:
  theme: forest
---
gantt
    title Gantt - Find My Roommate
    dateFormat  DD
    axisFormat  Giorno %d

    section SPRINT 1
    Docker (Lead)             :         T0.1, 01, 1d
    Directories (Lead)        :         T0.2, 01, 1d
    DB Users (Lead)           :         T1.1, 01, 1d
    API Register (Back)       :         T1.2, 01, 2d
    HTML Register (View)      :         T1.3, 01, 2d
    JS Register (Pres)        :         T1.4, 02, 2d
    API Login (Back)          :         T2.1, 03, 2d
    HTML Login (View)         :         T2.2, 03, 2d
    JS Login (Pres)           :         T2.3, 04, 2d
    Milestone M1              :         milestone, m1, 06, 0d

    section SPRINT 2
    DB Prefs (Lead)           :         T3.1, 05, 1d
    API Profile (Back)        :         T3.2, 05, 2d
    HTML Profile (View)       :         T3.3, 05, 2d
    JS Profile (Pres)         :         T3.4, 06, 2d
    DB Ads (Lead)             :         T4.1, 07, 1d
    API Ads CRUD (Back)       :         T4.2, 07, 2d
    HTML Dashboard (View)     :         T4.3, 07, 2d
    JS Ads CRUD (Pres)        :         T4.4, 08, 2d
    Milestone M2              :         milestone, m2, 10, 0d

    section SPRINT 3
    Algoritmo Match (Back)    :         T5.1, 09, 2d
    API Search (Back)         :         T5.2, 11, 2d
    HTML Results (View)       :         T6.1, 09, 2d
    JS Results (Pres)         :         T6.2, 10, 3d
    Milestone M3              :         milestone, m3, 13, 0d